export enum adminListUserEnum {
  GET_LIST_USER_REQUEST = 'APP/ADMIN/GET_LIST_USER_REQUEST',
  GET_LIST_USER_SUCCESS = 'APP/ADMIN/GET_LIST_USER_SUCCESS',
  GET_LIST_USER_FAILURE = 'APP/ADMIN/GET_LIST_USER_FAILURE',

  CLEAR_ADMIN_LIST_USER_STATE = 'APP/ADMIN/CLEAR_ADMIN_LIST_USER_STATE',
}
