export enum signInEnum {
  SIGN_IN_REQUEST = 'APP/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS = 'APP/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE = 'APP/SIGN_IN_FAILURE',

  CLEAR_SIGN_IN_STATE = 'APP/SIGN_IN_CLEAR_STATE',
}
